[package]
name = "rocket-pastebin"
version = "0.1.0"
authors = ["net-zero <net-zero@users.noreplay.github.com>"]

[dependencies]
rocket = "0.2.6"
rocket_codegen = "0.2.6"
rand = "0.3"

[dev-dependencies]
rocket = { version = "0.2.6", features = ["testing"] }
